# Generated by Django 4.2.2 on 2023-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
