# Generated by Django 4.2.2 on 2023-06-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0004_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='describtion',
            field=models.TextField(blank=True),
        ),
    ]
